// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd7diMEk9jAATF7LCQvjGTt8WwH9WB27A',
    appId: '1:840925347583:web:5698f074d48c22eaa716ca',
    messagingSenderId: '840925347583',
    projectId: 'aria-19f74',
    authDomain: 'aria-19f74.firebaseapp.com',
    storageBucket: 'aria-19f74.firebasestorage.app',
    measurementId: 'G-6BNMC423WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAew05cbKCYEXEPa410ZlRQvRonI08Hzh0',
    appId: '1:840925347583:android:06ced1eec1f89688a716ca',
    messagingSenderId: '840925347583',
    projectId: 'aria-19f74',
    storageBucket: 'aria-19f74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB369bqRuTEeese1HQLQaxZDnkUaR8EZ5E',
    appId: '1:840925347583:ios:0fef4cabce6d4d52a716ca',
    messagingSenderId: '840925347583',
    projectId: 'aria-19f74',
    storageBucket: 'aria-19f74.firebasestorage.app',
    iosBundleId: 'com.example.aria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB369bqRuTEeese1HQLQaxZDnkUaR8EZ5E',
    appId: '1:840925347583:ios:0fef4cabce6d4d52a716ca',
    messagingSenderId: '840925347583',
    projectId: 'aria-19f74',
    storageBucket: 'aria-19f74.firebasestorage.app',
    iosBundleId: 'com.example.aria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd7diMEk9jAATF7LCQvjGTt8WwH9WB27A',
    appId: '1:840925347583:web:0f2ebe14dd62149fa716ca',
    messagingSenderId: '840925347583',
    projectId: 'aria-19f74',
    authDomain: 'aria-19f74.firebaseapp.com',
    storageBucket: 'aria-19f74.firebasestorage.app',
    measurementId: 'G-MMHCCQQLXJ',
  );
}
